### ISSUE TITLE
Inquire about training the probability existence

### ISSUE THREAD

**Issue by mahmoudEltaher** [paschalidoud/superquadric_parsing#10]
Kindly I want to inquire about the probability existence

In the paper ,it said that the probability is trained after 20000 epochs ,how i can find this condition in the code ?

**Comment by paschalidoud** [comment]
Hi,

You need to specify the number of epochs. Please have a look at the arguments provided in the train_network.py script.

Best,
Despoina

**Comment by mahmoudEltaher** [comment]
Hi @paschalidoud 

Thanks for your collaboration.

I know how i can specify the number of epochs.

But i'm asking about this part in the paper "To further increase parsimony, we then fix all parameters
except γ for additional 5k iterations. This step removes remaining overlapping primitives as also observed in [37]."

how i can find this condition in the code ?
