### ISSUE TITLE
Inquire about the result 

### ISSUE THREAD

**Issue by mahmoudEltaher** [paschalidoud/superquadric_parsing#11]
Hi, @paschalidoud ,

When I run the following command ,for my new train model:
python scripts/forward_pass.py demo/03001627/ tmp/ --model_tag "1a6f615e8b1b5ae4dbbc9440457e303e" --n_primitives 20 --weight_file tmp/A708H5U1B/model_1 --train_with_bernoulli --use_sq --dataset_type shapenet_v2 --use_deformations

I got the following Result:
![image](https://user-images.githubusercontent.com/32056889/118627254-d8e40b80-b7cb-11eb-944c-9ed4362f742f.png)
[Results_with_deformation_with_ train_with_bernoull.zip](https://github.com/paschalidoud/superquadric_parsing/files/6500103/Results_with_deformation_with_.train_with_bernoull.zip)

After loading
0 0.99999845
1 3.4901092e-08
2 3.91378e-08
3 0.9999999
4 0.99999845
5 2.9896473e-08
6 3.784238e-08
7 0.99999964
8 0.99999964
9 3.9936218e-08
10 0.9999999
11 3.0588115e-08
12 0.9999999
13 0.99999917
14 3.5515406e-08
15 0.99999917
16 3.0844785e-08
17 0.99999976
18 0.9999989
19 3.0649847e-08
Using 11 primitives out of 20

Could you give some hints to solve this issue?
Thanks,

**Comment by paschalidoud** [comment]
Hi,

It seems that there is an issue with your model. Since you have posted the same question on another issue I am closing this for now and we can continue the discussion on the other thread.

Best,
Despoina
