### ISSUE TITLE
How I can prepare my own data for training the network

### ISSUE THREAD

**Issue by mahmoudEltaher** [paschalidoud/superquadric_parsing#12]
Kindly I want to inquire,how I can prepare my own data for training the network

**Comment by paschalidoud** [comment]
Hello,

If you have a specific question I would be more than happy to help. Other than that, please have a look [here](https://github.com/paschalidoud/superquadric_parsing/blob/master/learnable_primitives/common/model_factory.py) for the data loading.

Best,
Despoina
