### ISSUE TITLE
How can i use the ResNet18 rather than TulsianiNetwork

### ISSUE THREAD

**Issue by mahmoudEltaher** [paschalidoud/superquadric_parsing#13]
Kindly i want to inquire ,How can i use the ResNet18 rather than TulsianiNetwork

**Comment by paschalidoud** [comment]
Hi @mahmoudEltaher,

You should set the ``--architecture`` argument with resnet18. Please have a look [here](https://github.com/paschalidoud/superquadric_parsing/blob/19e365f012fb34c5997d2d5c28a5c121228d8063/scripts/arguments.py#L117)

Best,
Despoina

**Comment by mahmoudEltaher** [comment]
I know this , but I think Resnet dealing with images , so am I need another dataset to download, and am I need any other changes in the code.
