### ISSUE TITLE
Change the feature encoder to deal with point cloud directly 

### ISSUE THREAD

**Issue by mahmoudEltaher** [paschalidoud/superquadric_parsing#14]
Dear , 

can you give me a guide , how I can change the code to deal with point cloud directly. 

I want to train the model with ansi mechanical component set and the data set format is h5 files , is it possible ?

**Comment by paschalidoud** [comment]
Hello,

To train our network on point clouds you need to add a suitable neural network architecture that takes point-clouds as inputs and to also implement a class that would generate the input to the model. An example for the second is the [OccupancyGrid](https://github.com/paschalidoud/superquadric_parsing/blob/19e365f012fb34c5997d2d5c28a5c121228d8063/learnable_primitives/voxelizers.py#L34) and the [ImagePrecomputed](https://github.com/paschalidoud/superquadric_parsing/blob/19e365f012fb34c5997d2d5c28a5c121228d8063/learnable_primitives/voxelizers.py#L130).

Best,
Despoina
