### ISSUE TITLE
Inquire about VoxelizerFactory

### ISSUE THREAD

**Issue by mahmoudEltaher** [paschalidoud/superquadric_parsing#15]
Hi @paschalidoud 

Kindly i want to inquire about that:
In order to make the model deal with point cloud ,i need to make change in the VoxelizerFactory,but i'm not pretty sure what is the idea of this class and what i need to change if i want model deal with point-cloud.

Waiting for your kindly response.

**Comment by paschalidoud** [comment]
Hello,

The idea of the VoxelizerFactory is to provide an interface for easy experimentation with various types of input data e.g. images, pointclouds, voxels etc. To be able to use point clouds, you simply need to add a class that implements the interface [get_X(model)](https://github.com/paschalidoud/superquadric_parsing/blob/19e365f012fb34c5997d2d5c28a5c121228d8063/learnable_primitives/voxelizers.py#L110). You can have a look of how this is used [here](https://github.com/paschalidoud/superquadric_parsing/blob/19e365f012fb34c5997d2d5c28a5c121228d8063/learnable_primitives/common/dataset.py#L48).

I am closing this issue for now but please feel free to reopen if this is still not clear.

Best,
Despoina
