### ISSUE TITLE
Inquire about Encoder

### ISSUE THREAD

**Issue by mahmoudEltaher** [paschalidoud/superquadric_parsing#21]
Hi, @paschalidoud ,

I try to change the encoder of the model to accept point cloud,as it is mentioned in the paper.
I try to use PointNet but the output is not good ,I wonder if you try to change the model to accept point cloud.
If so can you share with me the code or advice about this matter.

waiting for you kindly advice.

**Comment by paschalidoud** [comment]
Hi @mahmoudEltaher,

You can also try using PointVCNN intstead https://github.com/mit-han-lab/pvcnn

From my experience it works better than PointNet. That being said, please note that also PointNet should work fine.

Best,
Despoina
