### ISSUE TITLE
Reproducing Table 1 in the paper

### ISSUE THREAD

**Issue by matheusgadelha** [paschalidoud/superquadric_parsing#5]
Congratulations for the work and thanks for open-sourcing the code!

I was looking at the results on Table 1 in the paper and they are very impressive. For example, comparing against the AtlasNet autoencder on chairs, their result is 0.0015, whereas yours is 0.0006. The same can be said for the airplanes (0.0008 vs 0.0003). However, visually inspecting the results, it seems that AtlasNet (and other methods) are much more detailed. Which is fine, since this project has a very different goal of summarizing the shapes as a set of superquadrics, but I would expect the Chamfer distance in the paper to be significantly higher.

Is there anything I am missing in the evaluation? Maybe the scale of the models is different? I would appreciate any comments regarding this issue.

**Comment by paschalidoud** [comment]
Thank you very much for your nice words and for your interest in our work.

Note that Table 1 reports the squared Chamfer-L2 loss and not the Chamfer-L1 loss as the AtlasNet paper. This is why the values are significantly lower. If you are interested in the Chamfer-L1 values for these 3 object categories, I am happy to evaluate our model again and send you these numbers.

I am closing the issue for now. But please feel free to reopen it in case there is still something unclear.

Best,
Despoina

**Comment by matheusgadelha** [comment]
Hi Despoina,

Thanks for your response! The number that I mentioned for AtlasNet is the one reported by running their autoencoder, which uses this code: https://github.com/ThibaultGROUEIX/ChamferDistancePytorch/blob/719b0f1ca5ba370616cb837c03ab88d9a88173ff/chamfer.cu#L35

I think their code is also computing squared Chamfer-L2, so I am not sure what is the source of the difference. Maybe the scale of the objects or the number of points used in the computation is different? How many points did you use to get the numbers in Table 1?
