### ISSUE TITLE
Can you provide the data set

### ISSUE THREAD

**Issue by mahmoudEltaher** [paschalidoud/superquadric_parsing#6]
I try to test the model by Running a command : forward_pass.py
but there is no directory called data 
and when i run on demo : 
forward_pass.py demo/03001627/ /tmp/ --model_tag "dac4af24e2facd7d3000ca4b
04fcd6ac" --n_primitives 18 --weight_file config/chair_T26AK2FES_model_699 --tra
in_with_bernoulli --use_deformations --use_sq --dataset_type shapenet_v2
it gives me : Found 1 'ShapeNetV2' models
and the image Result not chair  ? it is a strange shape 

![image](https://user-images.githubusercontent.com/32056889/96245781-005dc600-0fa8-11eb-9595-ee0251849770.png)

Appreciate your collaboration.

**Comment by paschalidoud** [comment]
Hello,

It seems as if you are not giving the correct path to the pre-trained weight file (defined with the argument --weight_file). As a result you are technically doing a forward pass on a network with random weights and thus the SQs are spheres. Just make sure that you properly provide the path to the weight file and it should work.

Best,
Despoina

**Comment by mahmoudEltaher** [comment]
This my full command 
python scripts/forward_pass.py demo/03001627/ /tmp/ --model_tag "dac4af24e2facd7d3000ca4b04fcd6ac" --n_primitives 18 --weight_file config/chair_T26AK2FES_model_699 --train_with_bernoulli --use_deformations --use_sq --dataset_type shapenet_v2
and this the result image 

![image](https://user-images.githubusercontent.com/32056889/96419677-c0d7e980-11f4-11eb-97d9-dced41e45cca.png)

These are the primitives output:

Found 1 'ShapeNetV2' models
1 models in total ...
0 0.5069658
1 0.5022032
2 0.49653435
3 0.54073983
4 0.48797867
5 0.5134207
6 0.4887344
7 0.46880084
8 0.5357602
9 0.5179657
10 0.5117862
11 0.50888073
12 0.48614326
13 0.5258909
14 0.4970924
15 0.46796083
16 0.48660067
17 0.5099754
Using 10 primitives out of 18
I already added the weight file,however it gives me the same result.

Important note when i run the code it give me this error 
line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TulsianiNetwork:
        Missing key(s) in state_dict: "_primitive_layer.layer0._tr

so i change these lines (by set strict to False),maybe this also cause a problem in parameter weight
        #model.load_state_dict(
        #    torch.load(args.weight_file, map_location=device)
        #)
         model.load_state_dict(
             torch.load(args.weight_file, map_location=device), strict=False
         )


Appreciate your collaboration.

-----------------------------------------
it seems that there is different in state-dict 

RuntimeError: Error(s) in loading state_dict for TulsianiNetwork:
        Missing key(s) in state_dict: 
		
		"_primitive_layer.layer0._translation_layer.weight", 
		"_primitive_layer.layer0._translation_layer.bias", 
		
		"_primitive_layer.layer1._rotation_layer.weight", 
		"_primitive_layer.layer1._rotation_layer.bias",
		
		"_primitive_layer.layer2._size_layer.weight", 
		"_primitive_layer.layer2._size_layer.bias", 
		
		"_primitive_layer.layer3._probability_layer.weight", 
		"_primitive_layer.layer3._probability_layer.bias", 
		
		"_primitive_layer.layer5._tapering_layer.weight", 
		"_primitive_layer.layer5._tapering_layer.bias".


        Unexpected key(s) in state_dict: 
		
		"_primitive_layer.layer0._size_layer.weight", 
		"_primitive_layer.layer0._size_layer.bias", 
		
		"_primitive_layer.layer1._translation_layer.weight", 
		"_primitive_layer.layer1._translation_layer.bias", 
		
		"_primitive_layer.layer2._rotation_layer.weight", 
		"_primitive_layer.layer2._rotation_layer.bias", 
		
		"_primitive_layer.layer3._tapering_layer.weight", 
		"_primitive_layer.layer3._tapering_layer.bias", 
		
		"_primitive_layer.layer5._probability_layer.weight", 
		"_primitive_layer.layer5._probability_layer.bias".

**Comment by mahmoudEltaher** [comment]
Kindly ,i want to inquire how i can change the model from tulsiani to resnet.

How to deal with the dataset? in this case

**Comment by paschalidoud** [comment]
Hi @mahmoudEltaher,

Did you manage to figure out this issue? You can change the model architecture from tulsiani to resnet via the ``--architecture argument``. Please see here https://github.com/paschalidoud/superquadric_parsing/blob/19e365f012fb34c5997d2d5c28a5c121228d8063/scripts/arguments.py#L121

I am closing the issue for now but please feel free to reopen it if you haven't figure out yet what is the issue.

Best,
Despoina
