### ISSUE TITLE
Configuration for reproduction of ShapeNet v2 Experiment

### ISSUE THREAD

**Issue by ktertikas** [paschalidoud/superquadric_parsing#7]
Hello @paschalidoud , thank you very much for the well-written codebase and paper! I wanted to ask some things related to the reproduction of the ShapeNet Core v2 dataset experiments. 

In particular, in the example of the README file, a suggested way of training the model on all chair data examples of ShapeNet is as follows:
```bash
./train_network.py ~/data/03001627/ /tmp/ --use_sq --lr 1e-4 --n_primitives 20 --train_with_bernoulli --dataset_type shapenet_v2 --use_chamfer
```

From what I can understand reading through the code, the loss used when running the above command does not include the `parsimony loss` mentioned in the paper. Could you let me know how to include this loss term? 

I can see there is indeed a `parsimony` loss in the codebase (link is [here](https://github.com/paschalidoud/superquadric_parsing/blob/19e365f012fb34c5997d2d5c28a5c121228d8063/learnable_primitives/regularizers.py#L38)), but this is not the same equation as the one mentioned in the paper.

Thank you for the very well-structured repo once again!

**Comment by mahmoudEltaher** [comment]
Hi @ktertikas 

I have same question, did you get any update 

thanks
