### ISSUE TITLE
Error : failed to update vertices

### ISSUE THREAD

**Issue by mahmoudEltaher** [paschalidoud/superquadric_parsing#8]
When i run the model with the following query :
python scripts/train_network.py ../03001627/ /tmp/ --use_sq --lr 1e-4 --n_primitives 20 --train_with_bernoulli --dataset_type shapenet_v2 --use_chamfer

I got the following error :

   1/2000 [..............................] - ETA: 3:11failed to update vertices
Traceback (most recent call last):
  File "C:\Users\Mahmoud Eltaher\Anaconda3\lib\site-packages\trimesh\exchange\wavefront.py", line 183, in append_mesh
    loaded['visual'].update_vertices(vert_order)
  File "C:\Users\Mahmoud Eltaher\Anaconda3\lib\site-packages\trimesh\visual\texture.py", line 162, in update_vertices
    self.uv = self.uv[mask]
IndexError: index 747 is out of bounds for axis 0 with size 170

Waiting for your kindly response.

**Comment by paschalidoud** [comment]
Hi @mahmoudEltaher,

It looks to me that this error is in trimesh. What is the name of the file that you are trying to open/load? Can you maybe share it here so that I can check as well?

Best,
Despoina

**Comment by paschalidoud** [comment]
Hi @mahmoudEltaher,

It seems that you figured out the issue with this, so I am closing this issue for now. But feel free to reopen it if you want.
